version: "3.8"
services:
  squarrels:
    container_name: squarrels_api
    extra_hosts:
      - ${SERVER}:172.18.0.3
    environment:
      WAIT_HOSTS: $MONGODB_HOST:${MONGODB_PORT}
    build: .
    ports:
      - "3000:3000"
      - "3100:3100"
    depends_on:
      - mongo
  mongo:
    container_name: squarrels_db
    image: mongo:4.2
    volumes:
      - ./data:/data/db
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
